-- MySQL Script generated by MySQL Workbench
-- Fri Jan  8 16:05:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

  -- -----------------------------------------------------
  -- Schema utopia
  -- -----------------------------------------------------
  CREATE SCHEMA IF NOT EXISTS `utopia`;
  USE `utopia`;
-- -----------------------------------------------------
  -- Table `utopia`.`tbl_airport`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_airport` (
    `iataIdent` VARCHAR(4) NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`iataIdent`)
  );
-- -----------------------------------------------------
  -- Table `utopia`.`tbl_users`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_users` (
    `userId` INT NOT NULL AUTO_INCREMENT,
    `password` VARCHAR(100) NOT NULL,
    `email` VARCHAR(50) NULL DEFAULT NULL,
    `firstName` VARCHAR(45) NOT NULL,
    `lastName` VARCHAR(45) NULL DEFAULT NULL,
    `enabled` TINYINT(1) NOT NULL,
    `locked` TINYINT(1) NOT NULL,
    `userRole` INT NULL DEFAULT NULL,
    PRIMARY KEY (`userId`),
    UNIQUE INDEX `tbl_users_email_uindex` (`email` ASC)
  );
-- -----------------------------------------------------
  -- Table `utopia`.`tbl_booking`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_booking` (
    `bookingId` INT NOT NULL AUTO_INCREMENT,
    `isActive` TINYINT NOT NULL,
    `stripeId` VARCHAR(45) NOT NULL,
    `bookerId` INT NOT NULL,
    PRIMARY KEY (`bookingId`),
    CONSTRAINT `fk_tbl_booking_tbl_users1` FOREIGN KEY (`bookerId`) REFERENCES `utopia`.`tbl_users` (`userId`)
  );
-- -----------------------------------------------------
  -- Table `utopia`.`tbl_traveler`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_traveler` (
    `travelerId` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `address` VARCHAR(45) NOT NULL,
    `phone` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `dob` DATETIME NOT NULL,
    PRIMARY KEY (`travelerId`)
  );
-- -----------------------------------------------------
  -- Table `utopia`.`tbl_bookings_has_travelers`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_bookings_has_travelers` (
    `bookingId` INT NOT NULL,
    `travelerId` INT NOT NULL,
    PRIMARY KEY (`bookingId`, `travelerId`),
    CONSTRAINT `fk_tbl_bookings_has_tbl_traveler_tbl_bookings1` FOREIGN KEY (`bookingId`) REFERENCES `utopia`.`tbl_booking` (`bookingId`),
    CONSTRAINT `fk_tbl_bookings_has_tbl_traveler_tbl_traveler1` FOREIGN KEY (`travelerId`) REFERENCES `utopia`.`tbl_traveler` (`travelerId`)
  );
  -- -----------------------------------------------------
-- Table `utopia`.`tbl_flight_details`
-- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_flight_details` (
    `flightNumber` VARCHAR(4) NOT NULL,
    `departCityId` VARCHAR(4) NULL DEFAULT NULL,
    `arriveCityId` VARCHAR(4) NULL DEFAULT NULL,
    PRIMARY KEY (`flightNumber`)
  );
-- -----------------------------------------------------
  -- Table `utopia`.`tbl_flight`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_flight` (
    `flightId` INT NOT NULL AUTO_INCREMENT,
    `departTime` DATETIME NOT NULL,
    `seatsAvailable` INT NOT NULL,
    `price` DECIMAL(13, 2) NOT NULL,
    `arrivalTime` DATETIME NOT NULL,
    `flightNumber` VARCHAR(4) NULL DEFAULT NULL,
    PRIMARY KEY (`flightId`),
    CONSTRAINT `tbl_flight_tbl_flight_details_flightNumber_fk` FOREIGN KEY (`flightNumber`) REFERENCES `utopia`.`tbl_flight_details` (`flightNumber`)
  );
-- -----------------------------------------------------
  -- Table `utopia`.`tbl_flight_has_bookings`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_flight_has_bookings` (
    `flightId` INT NOT NULL,
    `bookingId` INT NOT NULL,
    PRIMARY KEY (`flightId`, `bookingId`),
    CONSTRAINT `fk_tbl_flights_has_tbl_bookings_tbl_bookings1` FOREIGN KEY (`bookingId`) REFERENCES `utopia`.`tbl_booking` (`bookingId`),
    CONSTRAINT `fk_tbl_flights_has_tbl_bookings_tbl_flights1` FOREIGN KEY (`flightId`) REFERENCES `utopia`.`tbl_flight` (`flightId`)
  );
-- -----------------------------------------------------
  -- Table `utopia`.`tbl_user_signup_token`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `utopia`.`tbl_user_signup_token` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `confirmationToken` VARCHAR(100) NOT NULL,
    `createdDate` DATETIME NOT NULL,
    `userId` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `tbl_user_signup_token_confirmationToken_uindex` (`confirmationToken` ASC) ,
    CONSTRAINT `tbl_user_signup_token_tbl_users_userId_fk` FOREIGN KEY (`userId`) REFERENCES `utopia`.`tbl_users` (`userId`)
  );
-- -----------------------------------------------------
-- Table `utopia`.`tbl_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utopia`.`tbl_roles` (
  `userRole` INT NOT NULL,
  `roleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userRole`)
)