
server:
  port: 8100
  error:
    include-message: always

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/utopia-airlines
    username: ${SPRING_DB_UNAME}
    password: ${SPRING_DB_PASS}
    hikari:
         maximum-pool-size: 3
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        jdbc:
          time-zone: UTC
  jackson:
    deserialization:
      fail-on-unknown-properties: true
