server:
   port: 8085

spring:
   application:
      name: orchestrator
   datasource:
      url: jdbc:mysql://localhost:3306/utopia-airlines
      username: ${SPRING_DB_UNAME}
      password: ${SPRING_DB_PASS}
      hikari:
         maximum-pool-size: 3
   jpa:
      hibernate:
        naming:
           implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
           physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   mail:
      host: smtp.gmail.com
      port: 587
      username: ${GMAIL_USER}
      password: ${GMAIL_PASS}
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
               connectiontimeout: 5000
               timeout: 3000
               writetimeout: 5000

management:
   endpoints:
      web:
         exposure:
            include: "*"
